#!/usr/bin/env bash
REPLACE_STR="s/WHOAMI/$(whoami)/g"
sed -i ${REPLACE_STR} /app/.ngrok2/ngrok.yml

ssh_port=${SSH_PORT:-"2222"}

if [ -n "$NGROK_API_TOKEN" ]; then
  NGROK_OPTS="${NGROK_OPTS} --authtoken ${NGROK_API_TOKEN}"
fi

banner_file="/app/.ssh/banner.txt"
cat << EOF > ${banner_file}
+----------------------
| Welcome to SSH Relay!
+----------------------
EOF

echo "Starting sshd for $(whoami) on port ${ssh_port}"
/usr/sbin/sshd -f /app/.ssh/sshd_config -o "Port ${ssh_port}" -o "Banner ${banner_file}"

# Setup ngrok web port
echo "Setting up ngrok port"
REPLACE_STR="s/NGROK_PORT/${PORT}/g"
sed -i ${REPLACE_STR} /app/.ngrok2/ngrok.yml

# Start the tunnel
ngrok_cmd="ngrok tcp -log stdout ${NGROK_OPTS} ${ssh_port}"
echo "Starting ngrok tunnel"
eval "$ngrok_cmd &"

#########################################################################

REPLACE_STR="s/SSH_PORT/${ssh_port}/g"
sed -i ${REPLACE_STR} /app/conf/ssh-relay.conf

REPLACE_STR="s/PORT/${PORT}/g"
sed -i ${REPLACE_STR} /app/conf/ssh-relay.conf

/app/apache/bin/httpd -DNO_DETACH
